# Generated by Django 3.2 on 2021-05-01 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
